"""add audio_duration_seconds to answers

Revision ID: 7056f58880e7
Revises: f807ebee538d
Create Date: 2025-12-03 00:26:09.477206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7056f58880e7'
down_revision: Union[str, None] = 'f807ebee538d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('audio_duration_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'audio_duration_seconds')
    # ### end Alembic commands ###
